[Issue #371] Add NetNTLMv2 hash capture to README
GoSecure/pyrdp pull request #383
Opened 2022-01-07 21:43 UTC by lubiedo

@obilodeau Let me know if there's more to be added

2022-01-10 15:24 UTC, obilodeau requested changes
This addresses one portion of the request in https://github.com/GoSecure/pyrdp/issues/371. The other two need to be done as well.

2022-01-10 15:24 UTC, obilodeau commented on README.md
> +useful for research and offensivepurposes.
```suggestion
useful for research and offensive purposes.
```

2022-01-10 15:24 UTC, obilodeau commented on README.md
> +is not done via NLA as PyRDP will generate NTLMSSP messages by it's own and
This is inaccurate in non-NLA contexts. I should be further clarified.

2022-01-10 15:24 UTC, obilodeau commented on README.md
> +The captured NetNTLMv2 hash can be found in the logs and it's formatted so
say which log

2022-01-10 16:15 UTC, lubiedo commented
@obilodeau Committed some changes, let me know if everything is OK

2022-01-10 19:57 UTC, obilodeau reviewed
Did another round of review. The notes are mostly to myself, I think I should pick-it up from here.

2022-01-10 19:57 UTC, obilodeau commented on README.md
> +This will enable the possibility to intercept NLA enabled connections.
```suggestion
This will enable the possibility to intercept NLA-enforced connections.
```

2022-01-10 19:57 UTC, obilodeau commented on README.md
> +You can also specify the server's key and certificate along with the
TODO
- [ ] link to blogpost introducing the feature
- [ ] link to cert extraction documentation in `docs/`

2022-01-10 19:57 UTC, obilodeau commented on README.md
> +##### Monster-in-the-Middle NLA/CredSSP connections
Expand NLA to Network Level Authentication (NLA) the first time it is used

2022-01-10 19:57 UTC, obilodeau commented on README.md
> +connection to another non-NLA server to keep the connection alive. To enable
TODO
- [ ] more context about when to use this attack

2022-01-10 19:57 UTC, obilodeau commented on README.md
> +```
Add a diagram, I will also use it in the blog post since this was added in 1.1.0 which is covered by my next blog

2022-01-10 19:57 UTC, obilodeau commented on README.md
> +#### Capturing NetNTLMv2 hashes
TODO: Refer to Responder for people looking for a simpler tool

2022-01-10 19:57 UTC, obilodeau commented on README.md
> +as non-NLA (`tls`).
reword this to avoid talking about PyRDP's NLA/non-NLA (confusing)

2022-01-17 20:40 UTC, obilodeau commented
Dammit I screwed up, I brought in all changes in master since PR was created by accident... Review can focus on my last commit.

2022-01-17 21:51 UTC, obilodeau approved these changes
I finished the changes

2022-01-17 21:56 UTC, merged